# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 14:19
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter Valid Phone Number (10-digits)', regex='^\\d{10,10}$')])),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2017, 2, 15, 19, 49, 40, 88477))),
            ],
        ),
    ]
