# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0004_auto_20170215_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 15, 21, 27, 41, 776890)),
        ),
    ]
