# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 16:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0008_auto_20170215_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='reg_date',
        ),
        migrations.AddField(
            model_name='register',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 15, 21, 50, 51, 647289)),
        ),
    ]
