# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 17:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0014_auto_20170215_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='events',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('batman', 'Batman'), ('ironman', 'Ironman'), ('flash', 'Flash'), ('arrow', 'Arrow'), ('blackwidow', 'Black Widow')], default=None, max_length=37),
        ),
        migrations.AlterField(
            model_name='register',
            name='registd_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 15, 22, 33, 1, 259429)),
        ),
    ]
