# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0015_auto_20170215_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='registd_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 15, 23, 47, 44, 87919), editable=False),
        ),
    ]
