# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0018_auto_20170215_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='events',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Mad-Arts'), (2, 'Football'), (3, 'Cricket'), (4, 'Treasure-Hunt'), (5, 'Mr&Ms.Furore'), (6, 'Group-Dance'), (7, 'JAM'), (8, 'Sketching')], default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='register',
            name='registd_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 16, 21, 35, 36, 195206)),
        ),
    ]
