# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:43
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0020_auto_20170216_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='events',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('mad arts', 'Mad-Arts'), ('football', 'Football'), ('cricket', 'Cricket'), ('treasure hunt', 'Treasure-Hunt'), ('mr&ms furore', 'Mr&Ms.Furore'), ('group dance', 'Group-Dance'), ('jam', 'JAM'), ('sketching', 'Sketching')], default=None, max_length=78),
        ),
    ]
