# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:48
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0021_auto_20170217_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='events',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Mad-Arts'), (2, 'Football'), (3, 'Cricket'), (4, 'Treasure-Hunt'), (5, 'Mr&Ms.Furore'), (6, 'Group-Dance'), (7, 'JAM'), (8, 'Sketching')], default=None, max_length=15),
        ),
    ]
