# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0022_auto_20170217_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
