# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterApp', '0024_auto_20170225_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='reg_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='events',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Photography'), (2, 'Short-movie'), (3, 'Sketching'), (4, 'Painting'), (5, 'Campus-Painting'), (6, 'Crafts\\Installatiion'), (7, 'No-Idea'), (8, 'Face-Painting'), (9, 'Solo-Dance'), (10, 'Tapang'), (11, 'Western-Group'), (12, 'Indian-Group'), (13, 'Debate'), (14, 'JAM'), (15, 'Series-of-Unfortunate'), (16, 'Quiz(Genreal)'), (17, 'Pulp-Fiction'), (18, 'Battle-of-Bands'), (19, 'Instrumental-Solo'), (20, 'Western-Vox-Solo'), (21, 'Bollywood-Vox-Solo'), (22, 'Classical-Vox-Solo'), (23, 'Mad-Ads'), (24, 'Street-Paly'), (25, 'Mono-Acting'), (26, 'Dumb-charades'), (27, 'Standup-Comdey'), (30, 'Fashion-Show'), (31, 'Mr-&-Mrs-Furore'), (32, 'Crime-Connect-2.0'), (33, 'Fifa-Auction'), (34, 'Mini-Militia'), (35, 'DSI-Minute'), (36, 'Friends-Quiz'), (37, 'Carrom'), (38, 'Treasure-Hunt'), (39, 'Chuck-Glider'), (40, 'Code-Golfing'), (41, 'Corporate-Roadies'), (42, 'Tech-DC-and-Pictonary'), (43, 'Ideathon')], default=None, max_length=113),
        ),
    ]
